// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/khulnasoft/tunnel-db/pkg/db"
	"github.com/khulnasoft/tunnel/pkg/detector/ospkg"
	"github.com/khulnasoft/tunnel/pkg/fanal/applier"
	"github.com/khulnasoft/tunnel/pkg/fanal/cache"
	"github.com/khulnasoft/tunnel/pkg/scanner/local"
	"github.com/khulnasoft/tunnel/pkg/vulnerability"
)

// Injectors from inject.go:

func initializeScanServer(localArtifactCache cache.Cache) *ScanServer {
	v := _wireValue
	applierApplier := applier.NewApplier(localArtifactCache, v...)
	detector := ospkg.Detector{}
	config := db.Config{}
	client := vulnerability.NewClient(config)
	scanner := local.NewScanner(applierApplier, detector, client)
	scanServer := NewScanServer(scanner)
	return scanServer
}

var (
	_wireValue = []applier.Option(nil)
)
